//////////////////////////////////////////////////////////////////////
// LibFile: indices.scad
// Project: Strap Bender
// FileGroup: Data Model
// FileSummary: Named indexes for native Strap Bender record vectors.
//////////////////////////////////////////////////////////////////////

// Project specification
PR_RECORD_TYPE = 0;
PR_SCHEMA_VERSION = 1;
PR_NAME = 2;
PR_KIND = 3;
PR_STATUS = 4;
PR_NOTES = 5;

// Start pose specification
PO_RECORD_TYPE = 0;
PO_SCHEMA_VERSION = 1;
PO_X = 2;
PO_Y = 3;
PO_HEADING_DEGREES = 4;

// Bend-program command
CM_RECORD_TYPE = 0;
CM_SCHEMA_VERSION = 1;
CM_KIND = 2;
CM_SOURCE_INDEX = 3;
CM_DISTANCE = 4;
CM_ANGLE_DEGREES = 5;
CM_INSIDE_RADIUS = 6;
CM_LABEL = 7;

// Shape specification
SH_RECORD_TYPE = 0;
SH_SCHEMA_VERSION = 1;
SH_NAME = 2;
SH_CLOSURE = 3;
SH_START_POSE = 4;
SH_AUTHORING_KIND = 5;
SH_COMMANDS = 6;
SH_NOTES = 7;

// Derived analytical primitive
AP_RECORD_TYPE = 0;
AP_SCHEMA_VERSION = 1;
AP_KIND = 2;
AP_SOURCE_INDEX = 3;
AP_LABEL = 4;
AP_START_POSE = 5;
AP_END_POSE = 6;
AP_STATION_START = 7;
AP_STATION_END = 8;
AP_CENTER = 9;
AP_ANGLE_DEGREES = 10;
AP_INSIDE_RADIUS = 11;

// Derived analytical path
PA_RECORD_TYPE = 0;
PA_SCHEMA_VERSION = 1;
PA_NAME = 2;
PA_REFERENCE_AXIS = 3;
PA_CLOSURE = 4;
PA_START_POSE = 5;
PA_END_POSE = 6;
PA_PRIMITIVES = 7;
PA_BOUNDS = 8;
PA_NOTES = 9;

// Derived sampled display path
SP_RECORD_TYPE = 0;
SP_SCHEMA_VERSION = 1;
SP_NAME = 2;
SP_REFERENCE_AXIS = 3;
SP_CLOSURE = 4;
SP_POINTS = 5;
SP_CHORD_ERROR_MM = 6;
SP_MAX_ANGLE_STEP_DEGREES = 7;
SP_NOTES = 8;


// Numeric value schedule source
VS_RECORD_TYPE = 0;
VS_SCHEMA_VERSION = 1;
VS_KIND = 2;
VS_VALUES = 3;
VS_DEFAULT_VALUE = 4;
VS_SELECTED_VALUE = 5;
VS_INTERVAL = 6;
VS_FIRST_POSITION = 7;
VS_LABEL = 8;

// Vertex-polygon source specification
VP_RECORD_TYPE = 0;
VP_SCHEMA_VERSION = 1;
VP_NAME = 2;
VP_VERTICES = 3;
VP_CORNER_RADII = 4;
VP_START_VERTEX_INDEX = 5;
VP_NOTES = 6;

// Derived vertex-polygon corner
PC_RECORD_TYPE = 0;
PC_SCHEMA_VERSION = 1;
PC_SOURCE_VERTEX_INDEX = 2;
PC_VERTEX = 3;
PC_INCOMING_EDGE_INDEX = 4;
PC_OUTGOING_EDGE_INDEX = 5;
PC_TURN_ANGLE_DEGREES = 6;
PC_CLASSIFICATION = 7;
PC_INSIDE_RADIUS = 8;
PC_TANGENT_SETBACK = 9;
PC_ENTRY_POINT = 10;
PC_EXIT_POINT = 11;
PC_BEND_COMMAND_INDEX = 12;

// Derived vertex-polygon edge
PE_RECORD_TYPE = 0;
PE_SCHEMA_VERSION = 1;
PE_SOURCE_EDGE_INDEX = 2;
PE_START_VERTEX_INDEX = 3;
PE_END_VERTEX_INDEX = 4;
PE_START_POINT = 5;
PE_END_POINT = 6;
PE_RETAINED_LENGTH = 7;
PE_HEADING_DEGREES = 8;
PE_STRAIGHT_COMMAND_INDEX = 9;

// Derived vertex-polygon compilation
PX_RECORD_TYPE = 0;
PX_SCHEMA_VERSION = 1;
PX_SOURCE_POLYGON_NAME = 2;
PX_CORNERS = 3;
PX_EDGES = 4;
PX_NORMALIZED_SHAPE = 5;
PX_NOTES = 6;


// Regular-polygon source specification
RP_RECORD_TYPE = 0;
RP_SCHEMA_VERSION = 1;
RP_NAME = 2;
RP_SIDE_COUNT = 3;
RP_DIMENSION_KIND = 4;
RP_DIMENSION_VALUE = 5;
RP_CORNER_RADII = 6;
RP_CENTER = 7;
RP_FIRST_VERTEX_ANGLE_DEGREES = 8;
RP_START_VERTEX_INDEX = 9;
RP_NOTES = 10;

// Derived regular-polygon compilation
RX_RECORD_TYPE = 0;
RX_SCHEMA_VERSION = 1;
RX_SOURCE_POLYGON_NAME = 2;
RX_RESOLVED_CIRCUMRADIUS = 3;
RX_RESOLVED_APOTHEM = 4;
RX_RESOLVED_SIDE_LENGTH = 5;
RX_VERTICES = 6;
RX_GENERATED_VERTEX_POLYGON = 7;
RX_NOTES = 8;

// Reusable pattern element
PT_RECORD_TYPE = 0;
PT_SCHEMA_VERSION = 1;
PT_KIND = 2;
PT_DISTANCE_PARAMETER = 3;
PT_ANGLE_PARAMETER = 4;
PT_RADIUS_PARAMETER = 5;
PT_ANGLE_MULTIPLIER = 6;
PT_LABEL = 7;

// Reusable pattern block
PB_RECORD_TYPE = 0;
PB_SCHEMA_VERSION = 1;
PB_NAME = 2;
PB_ELEMENTS = 3;
PB_NOTES = 4;

// Pattern parameter assignment
PP_RECORD_TYPE = 0;
PP_SCHEMA_VERSION = 1;
PP_NAME = 2;
PP_VALUE_SOURCE = 3;
PP_LABEL = 4;

// Pattern repetition instance
PI_RECORD_TYPE = 0;
PI_SCHEMA_VERSION = 1;
PI_NAME = 2;
PI_PATTERN_NAME = 3;
PI_REPEAT_COUNT = 4;
PI_PARAMETERS = 5;
PI_CLOSURE = 6;
PI_START_POSE = 7;
PI_NOTES = 8;

// Expanded-command provenance
PV_RECORD_TYPE = 0;
PV_SCHEMA_VERSION = 1;
PV_COMMAND_INDEX = 2;
PV_REPETITION_INDEX = 3;
PV_LOCAL_ELEMENT_INDEX = 4;
PV_LOCAL_LABEL = 5;

// Derived pattern compilation
PCX_RECORD_TYPE = 0;
PCX_SCHEMA_VERSION = 1;
PCX_SOURCE_INSTANCE_NAME = 2;
PCX_SOURCE_PATTERN_NAME = 3;
PCX_RESOLVED_PARAMETERS = 4;
PCX_PROVENANCE = 5;
PCX_NORMALIZED_SHAPE = 6;
PCX_NOTES = 7;
